# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.URLField(db_index=True)),
                ('paragraph_hash', models.BigIntegerField(db_index=True)),
                ('comment_hash', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('article_url', 'paragraph_hash', 'timestamp'),
            },
        ),
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('login', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('avatar_url', models.URLField()),
                ('banned', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_app_comments.Commenter'),
        ),
    ]
