# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='avatar_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
