# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='Andrew M. Farrell', max_length=128),
            preserve_default=False,
        ),
    ]
