# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app_comments', '0002_comment_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('article_url', 'paragraph_hash', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article_slug',
        ),
        migrations.AddField(
            model_name='comment',
            name='article_url',
            field=models.URLField(db_index=True, default='http://0.0.0.0:8000/saltstack-from-scratch/'),
            preserve_default=False,
        ),
    ]
