# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app_comments', '0002_auto_20160117_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
