# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app_comments', '0003_auto_20160104_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_avatar_url',
            field=models.URLField(default='https://avatars.githubusercontent.com/u/123831?v=3'),
            preserve_default=False,
        ),
    ]
